version: "3"

services:
  spark-master:
    image: spark-master
    command: spark-class org.apache.spark.deploy.master.Master
    ports:
    - "8080:8080"
    - "7077:7077"
  spark-worker-1:
    image: spark-worker
    command: spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_MEMORY=8G"
      - "SPARK_WORKER_CORES=3"
      
  spark-worker-2:
    image: spark-worker
    command: spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_MEMORY=8G"
      - "SPARK_WORKER_CORES=3"

  spark-worker-3:
    image: spark-worker
    command: spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_MEMORY=8G"
      - "SPARK_WORKER_CORES=3"

  jupyter-notebook:
    image: jupyter/all-spark-notebook:latest
    depends_on:
      - spark-master
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/data
